"""Route registration helpers for ARIApp."""


def register_static_routes(app):
    """Register static auth/user/admin/docs API routes."""
    _lim = app._limiter

    # Registration and account APIs — rate-limited
    app.add_url_rule(
        "/api/auth/register/start",
        "api_auth_register_start",
        _lim.limit("5 per minute; 20 per hour")(app._api_auth_register_start),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/auth/register/verify",
        "api_auth_register_verify",
        _lim.limit("10 per minute; 30 per hour")(app._api_auth_register_verify),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/account/get",
        "api_user_account_get",
        app._api_user_account_get,
    )
    app.add_url_rule(
        "/api/user/account/update",
        "api_user_account_update",
        app._api_user_account_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/account/request-primary-email",
        "api_user_account_request_primary_email",
        app._api_user_account_request_primary_email,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/account/confirm-primary-email",
        "api_user_account_confirm_primary_email",
        app._api_user_account_confirm_primary_email,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/data-access-request",
        "api_user_data_access_request",
        app._api_user_data_access_request,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/pins/list", "api_user_pins_list", app._api_user_pins_list
    )
    app.add_url_rule(
        "/api/user/pins/toggle",
        "api_user_pins_toggle",
        app._api_user_pins_toggle,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/pins/remove",
        "api_user_pins_remove",
        app._api_user_pins_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/pins/reorder",
        "api_user_pins_reorder",
        app._api_user_pins_reorder,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/object-sections/get",
        "api_user_object_sections_get",
        app._api_user_object_sections_get,
    )
    app.add_url_rule(
        "/api/user/object-sections/toggle",
        "api_user_object_sections_toggle",
        app._api_user_object_sections_toggle,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/object-sections/reorder",
        "api_user_object_sections_reorder",
        app._api_user_object_sections_reorder,
        methods=["POST"],
    )

    # User links API routes
    app.add_url_rule(
        "/api/user/links/get", "api_user_links_get", app._api_user_links_get
    )
    app.add_url_rule(
        "/api/user/links/add",
        "api_user_links_add",
        app._api_user_links_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/links/update",
        "api_user_links_update",
        app._api_user_links_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/links/remove",
        "api_user_links_remove",
        app._api_user_links_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/links/add-section",
        "api_user_links_add_section",
        app._api_user_links_add_section,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/links/remove-section",
        "api_user_links_remove_section",
        app._api_user_links_remove_section,
        methods=["POST"],
    )

    # User notes API routes
    app.add_url_rule(
        "/api/user/notes/list", "api_user_notes_list", app._api_user_notes_list
    )
    app.add_url_rule(
        "/api/user/notes/get", "api_user_notes_get", app._api_user_notes_get
    )
    app.add_url_rule(
        "/api/user/notes/save",
        "api_user_notes_save",
        app._api_user_notes_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/notes/delete",
        "api_user_notes_delete",
        app._api_user_notes_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/notes/render",
        "api_user_notes_render",
        app._api_user_notes_render,
        methods=["POST"],
    )

    # User preferences API routes
    app.add_url_rule(
        "/api/user/prefs/get", "api_user_prefs_get", app._api_user_prefs_get
    )
    app.add_url_rule(
        "/api/user/prefs/save",
        "api_user_prefs_save",
        app._api_user_prefs_save,
        methods=["POST"],
    )

    # User calendar API routes
    app.add_url_rule(
        "/api/user/calendar/list",
        "api_user_calendar_list",
        app._api_user_calendar_list,
    )
    app.add_url_rule(
        "/api/user/calendar/save",
        "api_user_calendar_save",
        app._api_user_calendar_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/calendar/delete",
        "api_user_calendar_delete",
        app._api_user_calendar_delete,
        methods=["POST"],
    )

    # User ICS feed routes
    app.add_url_rule(
        "/api/user/calendar/ics/list",
        "api_user_ics_list",
        app._api_user_ics_list,
    )
    app.add_url_rule(
        "/api/user/calendar/ics/add",
        "api_user_ics_add",
        app._api_user_ics_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/calendar/ics/delete",
        "api_user_ics_delete",
        app._api_user_ics_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/calendar/ics/refresh",
        "api_user_ics_refresh",
        app._api_user_ics_refresh,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/calendar/ics/edit",
        "api_user_ics_edit",
        app._api_user_ics_edit,
        methods=["POST"],
    )

    # User todo API routes
    app.add_url_rule(
        "/api/user/todo/list", "api_user_todo_list", app._api_user_todo_list
    )
    app.add_url_rule(
        "/api/user/todo/save",
        "api_user_todo_save",
        app._api_user_todo_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/todo/toggle",
        "api_user_todo_toggle",
        app._api_user_todo_toggle,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/todo/delete",
        "api_user_todo_delete",
        app._api_user_todo_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/todo/reorder",
        "api_user_todo_reorder",
        app._api_user_todo_reorder,
        methods=["POST"],
    )

    # Admin calendar API routes
    app.add_url_rule(
        "/api/admin/calendar/list",
        "api_admin_calendar_list",
        app._api_admin_calendar_list,
    )
    app.add_url_rule(
        "/api/admin/calendar/save",
        "api_admin_calendar_save",
        app._api_admin_calendar_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/calendar/delete",
        "api_admin_calendar_delete",
        app._api_admin_calendar_delete,
        methods=["POST"],
    )

    # Admin ICS feed routes
    app.add_url_rule(
        "/api/admin/calendar/ics/list",
        "api_admin_ics_list",
        app._api_admin_ics_list,
    )
    app.add_url_rule(
        "/api/admin/calendar/ics/add",
        "api_admin_ics_add",
        app._api_admin_ics_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/calendar/ics/delete",
        "api_admin_ics_delete",
        app._api_admin_ics_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/calendar/ics/refresh",
        "api_admin_ics_refresh",
        app._api_admin_ics_refresh,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/calendar/ics/edit",
        "api_admin_ics_edit",
        app._api_admin_ics_edit,
        methods=["POST"],
    )

    # Admin links API routes
    app.add_url_rule(
        "/api/admin/links/get", "api_admin_links_get", app._api_admin_links_get
    )
    app.add_url_rule(
        "/api/admin/links/add",
        "api_admin_links_add",
        app._api_admin_links_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/links/update",
        "api_admin_links_update",
        app._api_admin_links_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/links/remove",
        "api_admin_links_remove",
        app._api_admin_links_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/links/add-section",
        "api_admin_links_add_section",
        app._api_admin_links_add_section,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/links/remove-section",
        "api_admin_links_remove_section",
        app._api_admin_links_remove_section,
        methods=["POST"],
    )

    # Admin email API routes
    app.add_url_rule(
        "/api/admin/email/test",
        "api_admin_email_test",
        app._api_admin_email_test,
    )
    app.add_url_rule(
        "/api/admin/email/save",
        "api_admin_email_save",
        app._api_admin_email_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/email/send-test",
        "api_admin_email_send_test",
        app._api_admin_email_send_test,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/test",
        "api_admin_backups_test",
        app._api_admin_backups_test,
    )
    app.add_url_rule(
        "/api/admin/backups/oauth/start",
        "api_admin_backups_oauth_start",
        app._api_admin_backups_oauth_start,
    )
    app.add_url_rule(
        "/api/admin/backups/oauth/callback",
        "api_admin_backups_oauth_callback",
        app._api_admin_backups_oauth_callback,
    )
    app.add_url_rule(
        "/api/admin/backups/test-backup",
        "api_admin_backups_test_backup",
        app._api_admin_backups_test_backup,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/save",
        "api_admin_backups_save",
        app._api_admin_backups_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/upload-json",
        "api_admin_backups_upload_json",
        app._api_admin_backups_upload_json,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/list",
        "api_admin_backups_list",
        app._api_admin_backups_list,
    )
    app.add_url_rule(
        "/api/admin/backups/delete",
        "api_admin_backups_delete",
        app._api_admin_backups_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/delete-all",
        "api_admin_backups_delete_all",
        app._api_admin_backups_delete_all,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/sync",
        "api_admin_backups_sync",
        app._api_admin_backups_sync,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/download",
        "api_admin_backups_download",
        app._api_admin_backups_download,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/sync-from-cloud",
        "api_admin_backups_sync_from_cloud",
        app._api_admin_backups_sync_from_cloud,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/backups/browse",
        "api_admin_backups_browse",
        app._api_admin_backups_browse,
    )
    app.add_url_rule(
        "/api/admin/backups/validate-dir",
        "api_admin_backups_validate_dir",
        app._api_admin_backups_validate_dir,
    )

    # SSHFS management routes
    app.add_url_rule(
        "/api/admin/sshfs/keys/list",
        "api_admin_sshfs_keys_list",
        app._api_admin_sshfs_keys_list,
    )
    app.add_url_rule(
        "/api/admin/sshfs/keys/add",
        "api_admin_sshfs_keys_add",
        app._api_admin_sshfs_keys_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/keys/delete/<key_name>",
        "api_admin_sshfs_keys_delete",
        app._api_admin_sshfs_keys_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/add",
        "api_admin_sshfs_mounts_add",
        app._api_admin_sshfs_mounts_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/update/<mount_name>",
        "api_admin_sshfs_mounts_update",
        app._api_admin_sshfs_mounts_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/test-connection",
        "api_admin_sshfs_mounts_test_connection",
        app._api_admin_sshfs_mounts_test_connection,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/delete/<mount_name>",
        "api_admin_sshfs_mounts_delete",
        app._api_admin_sshfs_mounts_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/mount/<mount_name>",
        "api_admin_sshfs_mounts_mount",
        app._api_admin_sshfs_mounts_mount,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/unmount/<mount_name>",
        "api_admin_sshfs_mounts_unmount",
        app._api_admin_sshfs_mounts_unmount,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/unmount-lazy/<mount_name>",
        "api_admin_sshfs_mounts_unmount_lazy",
        app._api_admin_sshfs_mounts_unmount_lazy,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/status",
        "api_admin_sshfs_mounts_status",
        app._api_admin_sshfs_mounts_status,
    )
    app.add_url_rule(
        "/api/admin/sshfs/mounts/log/<mount_name>",
        "api_admin_sshfs_mounts_log",
        app._api_admin_sshfs_mounts_log,
    )

    # Interactive SSH terminal routes
    app.add_url_rule(
        "/api/admin/sshfs/interactive/start-test",
        "api_admin_sshfs_interactive_start_test",
        app._api_admin_sshfs_interactive_start_test,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/interactive/start-mount",
        "api_admin_sshfs_interactive_start_mount",
        app._api_admin_sshfs_interactive_start_mount,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/interactive/poll",
        "api_admin_sshfs_interactive_poll",
        app._api_admin_sshfs_interactive_poll,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/interactive/send",
        "api_admin_sshfs_interactive_send",
        app._api_admin_sshfs_interactive_send,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sshfs/interactive/close",
        "api_admin_sshfs_interactive_close",
        app._api_admin_sshfs_interactive_close,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/health/update",
        "api_admin_health_update",
        app._api_admin_health_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/audit-log",
        "api_admin_audit_log",
        app._api_admin_audit_log,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/health-history",
        "api_admin_health_history",
        app._api_admin_health_history,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/health/patch",
        "api_admin_health_patch",
        app._api_admin_health_patch,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/health/config",
        "api_admin_health_config_get",
        app._api_admin_health_config_get,
    )
    app.add_url_rule(
        "/api/admin/health/config",
        "api_admin_health_config_save",
        app._api_admin_health_config_save,
        methods=["POST"],
    )

    # Plot cache admin routes
    app.add_url_rule(
        "/api/admin/cache/save",
        "api_admin_cache_save",
        app._api_admin_cache_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/cache/purge",
        "api_admin_cache_purge",
        app._api_admin_cache_purge,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/cache/reset-timings",
        "api_admin_cache_reset_timings",
        app._api_admin_cache_reset_timings,
        methods=["POST"],
    )

    # Download management admin routes
    app.add_url_rule(
        "/api/admin/dm/save-settings",
        "api_admin_dm_save_settings",
        app._api_admin_dm_save_settings,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/dm/reset-user",
        "api_admin_dm_reset_user",
        app._api_admin_dm_reset_user,
        methods=["POST"],
    )

    # User API token routes
    app.add_url_rule(
        "/api/user/token/generate",
        "api_user_token_generate",
        app._api_user_token_generate,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/token/revoke",
        "api_user_token_revoke",
        app._api_user_token_revoke,
        methods=["POST"],
    )

    # Documentation routes (edit, save, upload, images)
    app.add_url_rule(
        "/docs/<path:page_ref>/edit",
        "doc_edit",
        app._doc_edit_view,
    )
    app.add_url_rule(
        "/docs/<path:page_ref>/save",
        "doc_save",
        app._doc_save_view,
        methods=["POST"],
    )
    app.add_url_rule(
        "/docs/upload-image",
        "doc_upload_image",
        app._doc_upload_image,
        methods=["POST"],
    )
    app.add_url_rule(
        "/docs/<path:page_ref>",
        "doc_dynamic_view",
        app._doc_dynamic_view,
    )
    app.add_url_rule("/doc-images/<path:filename>", "doc_image", app._doc_image_view)

    # Admin user management API routes
    app.add_url_rule(
        "/api/admin/users/search", "api_user_search", app._api_user_search
    )
    app.add_url_rule(
        "/api/admin/users/update-groups",
        "api_user_update_groups",
        app._api_user_update_groups,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/users/update-instruments",
        "api_user_update_instruments",
        app._api_user_update_instruments,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/users/delete",
        "api_user_delete",
        app._api_user_delete,
        methods=["POST"],
    )

    # Admin login-as API routes
    app.add_url_rule(
        "/api/admin/login-as/search",
        "api_login_as_search",
        app._api_login_as_search,
    )
    app.add_url_rule(
        "/api/admin/login-as/set",
        "api_login_as_set",
        app._api_login_as_set,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/login-as/clear",
        "api_login_as_clear",
        app._api_login_as_clear,
        methods=["POST"],
    )

    # Admin science groups API routes
    app.add_url_rule(
        "/api/admin/sci-groups/list",
        "api_sci_groups_list",
        app._api_sci_groups_list,
    )
    app.add_url_rule(
        "/api/admin/sci-groups/get",
        "api_sci_groups_get",
        app._api_sci_groups_get,
    )
    app.add_url_rule(
        "/api/admin/sci-groups/save",
        "api_sci_groups_save",
        app._api_sci_groups_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/save-all",
        "api_sci_groups_save_all",
        app._api_sci_groups_save_all,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/create",
        "api_sci_groups_create",
        app._api_sci_groups_create,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/delete",
        "api_sci_groups_delete",
        app._api_sci_groups_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/refresh-run-ids",
        "api_sci_groups_refresh_run_ids",
        app._api_sci_groups_refresh_run_ids,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/export",
        "api_sci_groups_export",
        app._api_sci_groups_export,
    )
    app.add_url_rule(
        "/api/admin/sci-groups/import",
        "api_sci_groups_import",
        app._api_sci_groups_import,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/sci-groups/io/export",
        "api_sci_groups_io_export",
        app._api_sci_groups_io_export,
    )
    app.add_url_rule(
        "/api/admin/sci-groups/io/import",
        "api_sci_groups_io_import",
        app._api_sci_groups_io_import,
        methods=["POST"],
    )

    # Admin APERO profiles API routes
    app.add_url_rule(
        "/api/admin/apero-profiles/list",
        "api_apero_profiles_list",
        app._api_apero_profiles_list,
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/overview-status",
        "api_apero_profiles_overview",
        app._api_apero_profiles_overview,
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/save",
        "api_apero_profiles_save",
        app._api_apero_profiles_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/save-temporary",
        "api_apero_profiles_save_temporary",
        app._api_apero_profiles_save_temporary,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/delete",
        "api_apero_profiles_delete",
        app._api_apero_profiles_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/reorder",
        "api_apero_profiles_reorder",
        app._api_apero_profiles_reorder,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/validate-path",
        "api_apero_profiles_validate",
        app._api_apero_profiles_validate,
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/browse",
        "api_apero_profiles_browse",
        app._api_apero_profiles_browse,
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/update-groups",
        "api_apero_profiles_update_groups",
        app._api_apero_profiles_update_groups,
        methods=["POST"],
    )
    app.add_url_rule(
        '/api/admin/apero-profiles/toggle-disabled',
        'api_apero_profiles_toggle_disabled',
        app._api_apero_profiles_toggle_disabled,
        methods=['POST'],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/test-db",
        "api_apero_profiles_test_db",
        app._api_apero_profiles_test_db,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/list-tables",
        "api_apero_profiles_list_tables",
        app._api_apero_profiles_list_tables,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/test-tables",
        "api_apero_profiles_test_tables",
        app._api_apero_profiles_test_tables,
        methods=["POST"],
    )

    # Interactive SSH tunnel for APERO profile DB connections
    app.add_url_rule(
        "/api/admin/apero-profiles/ssh-tunnel/start",
        "api_apero_profiles_ssh_tunnel_start",
        app._api_apero_profiles_ssh_tunnel_start,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/ssh-tunnel/poll",
        "api_apero_profiles_ssh_tunnel_poll",
        app._api_apero_profiles_ssh_tunnel_poll,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/ssh-tunnel/send",
        "api_apero_profiles_ssh_tunnel_send",
        app._api_apero_profiles_ssh_tunnel_send,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/apero-profiles/ssh-tunnel/close",
        "api_apero_profiles_ssh_tunnel_close",
        app._api_apero_profiles_ssh_tunnel_close,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/status",
        "api_db_ssh_tunnel_status",
        app._api_db_ssh_tunnel_status,
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/list",
        "api_db_ssh_tunnel_list",
        app._api_db_ssh_tunnel_list,
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/ssh-hosts",
        "api_db_ssh_tunnel_ssh_hosts",
        app._api_db_ssh_tunnel_ssh_hosts,
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/save",
        "api_db_ssh_tunnel_save",
        app._api_db_ssh_tunnel_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/delete",
        "api_db_ssh_tunnel_delete",
        app._api_db_ssh_tunnel_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/ensure",
        "api_db_ssh_tunnel_ensure",
        app._api_db_ssh_tunnel_ensure,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/test",
        "api_db_ssh_tunnel_test",
        app._api_db_ssh_tunnel_test,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/db-ssh-tunnel/close",
        "api_db_ssh_tunnel_close",
        app._api_db_ssh_tunnel_close,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/database-setup/local-db/list",
        "api_database_setup_local_db_list",
        app._api_database_setup_local_db_list,
    )
    app.add_url_rule(
        "/api/admin/database-setup/local-db/save",
        "api_database_setup_local_db_save",
        app._api_database_setup_local_db_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/database-setup/local-db/delete",
        "api_database_setup_local_db_delete",
        app._api_database_setup_local_db_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/database-setup/local-db/test",
        "api_database_setup_local_db_test",
        app._api_database_setup_local_db_test,
        methods=["POST"],
    )

    # Admin user DB access API routes
    app.add_url_rule(
        "/api/admin/user-db-access/profiles",
        "api_user_db_access_profiles",
        app._api_user_db_access_profiles,
    )
    app.add_url_rule(
        "/api/admin/user-db-access/details",
        "api_user_db_access_details",
        app._api_user_db_access_details,
    )
    app.add_url_rule(
        "/api/admin/user-db-access/health-check",
        "api_user_db_access_health_check",
        app._api_user_db_access_health_check,
    )
    app.add_url_rule(
        "/api/admin/user-db-access/save",
        "api_user_db_access_save",
        app._api_user_db_access_save,
        methods=["POST"],
    )

    # Async tasks API routes
    app.add_url_rule(
        "/api/admin/async-tasks/list",
        "api_async_tasks_list",
        app._api_async_tasks_list,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/global-list",
        "api_async_tasks_global_list",
        app._api_async_tasks_global_list,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/task-list",
        "api_async_tasks_task_list",
        app._api_async_tasks_task_list,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/save",
        "api_async_tasks_save",
        app._api_async_tasks_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/delete",
        "api_async_tasks_delete",
        app._api_async_tasks_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/reorder",
        "api_async_tasks_reorder",
        app._api_async_tasks_reorder,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/toggle",
        "api_async_tasks_toggle",
        app._api_async_tasks_toggle,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/run-now",
        "api_async_tasks_run_now",
        app._api_async_tasks_run_now,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/run-all",
        "api_async_tasks_run_all",
        app._api_async_tasks_run_all,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/stop",
        "api_async_tasks_stop",
        app._api_async_tasks_stop,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/kill-all",
        "api_async_tasks_kill_all",
        app._api_async_tasks_kill_all,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/clear-history",
        "api_async_tasks_clear_history",
        app._api_async_tasks_clear_history,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/status",
        "api_async_tasks_status",
        app._api_async_tasks_status,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/task-log",
        "api_async_tasks_task_log",
        app._api_async_tasks_task_log,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/cancel-task",
        "api_async_tasks_cancel_task",
        app._api_async_tasks_cancel_task,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/read-file",
        "api_async_tasks_read_file",
        app._api_async_tasks_read_file,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/download-file",
        "api_async_tasks_download_file",
        app._api_async_tasks_download_file,
    )
    app.add_url_rule(
        "/api/admin/async-tasks/gsheet-oauth-start",
        "api_async_tasks_gsheet_oauth_start",
        app._api_async_tasks_gsheet_oauth_start,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/async-tasks/gsheet-oauth-callback",
        "api_async_tasks_gsheet_oauth_callback",
        app._api_async_tasks_gsheet_oauth_callback,
        methods=["GET"],
    )


def register_data_portal_routes(app):
    """Register Data Portal profile, object, basket, and API routes."""
    app.add_url_rule(
        "/data_portal/<profile_id>", "ri_profile", app._ri_profile_view
    )

    # Data portal profile health-check API
    app.add_url_rule(
        "/api/ri/profile-health",
        "api_ri_profile_health",
        app._api_ri_profile_health,
        methods=["POST"],
    )

    # Object table sub-page + data API
    app.add_url_rule(
        "/api/data-portal/profiles", "api_profiles_list", app._api_profiles_list
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/object-table",
        "ri_object_table",
        app._ri_object_table_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/find-object",
        "ri_find_object",
        app._ri_find_object_view,
    )
    app.add_url_rule(
        "/api/data-portal/object-table",
        "api_object_table",
        app._api_object_table,
    )
    app.add_url_rule(
        "/api/astrometrics/find-object",
        "api_astrometrics_find_object",
        app._api_astrometrics_find_object,
    )
    app.add_url_rule(
        "/api/astrometrics/resolve-by-name",
        "api_astrometrics_resolve_by_name",
        app._api_astrometrics_resolve_by_name,
    )
    app.add_url_rule(
        "/api/astrometrics/resolve-by-coords",
        "api_astrometrics_resolve_by_coords",
        app._api_astrometrics_resolve_by_coords,
    )
    app.add_url_rule(
        "/api/astrometrics/resolve-by-filter",
        "api_astrometrics_resolve_by_filter",
        app._api_astrometrics_resolve_by_filter,
    )
    app.add_url_rule(
        "/api/astrometrics/columns",
        "api_astrometrics_columns",
        app._api_astrometrics_columns,
    )
    app.add_url_rule(
        "/api/astrometrics/list-all",
        "api_astrometrics_list_all",
        app._api_astrometrics_list_all,
    )
    app.add_url_rule(
        "/api/astrometrics/list-rejected",
        "api_astrometrics_list_rejected",
        app._api_astrometrics_list_rejected,
    )
    app.add_url_rule(
        "/api/astrometrics/add-rejected",
        "api_astrometrics_add_rejected",
        app._api_astrometrics_add_rejected,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/update-rejected",
        "api_astrometrics_update_rejected",
        app._api_astrometrics_update_rejected,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/delete-rejected",
        "api_astrometrics_delete_rejected",
        app._api_astrometrics_delete_rejected,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/add-manual",
        "api_astrometrics_add_manual",
        app._api_astrometrics_add_manual,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/recompute-manual",
        "api_astrometrics_recompute_manual",
        app._api_astrometrics_recompute_manual,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/lock/acquire",
        "api_astrometrics_lock_acquire",
        app._api_astrometrics_lock_acquire,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/lock/heartbeat",
        "api_astrometrics_lock_heartbeat",
        app._api_astrometrics_lock_heartbeat,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/lock/release",
        "api_astrometrics_lock_release",
        app._api_astrometrics_lock_release,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/history/list",
        "api_astrometrics_history_list",
        app._api_astrometrics_history_list,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/astrometrics/history/delete",
        "api_astrometrics_history_delete",
        app._api_astrometrics_history_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/history/clear",
        "api_astrometrics_history_clear",
        app._api_astrometrics_history_clear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/list",
        "api_rejection_list_list",
        app._api_rejection_list_list,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/rejection-list/add",
        "api_rejection_list_add",
        app._api_rejection_list_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/update",
        "api_rejection_list_update",
        app._api_rejection_list_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/delete",
        "api_rejection_list_delete",
        app._api_rejection_list_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/upload",
        "api_rejection_list_upload",
        app._api_rejection_list_upload,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/list",
        "api_rejection_history_list",
        app._api_rejection_history_list,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/get",
        "api_rejection_history_get",
        app._api_rejection_history_get,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/restore",
        "api_rejection_history_restore",
        app._api_rejection_history_restore,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/resolve",
        "api_rejection_history_resolve",
        app._api_rejection_history_resolve,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/delete",
        "api_rejection_history_delete",
        app._api_rejection_history_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/rejection-list/history/clear",
        "api_rejection_history_clear",
        app._api_rejection_history_clear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/history/get",
        "api_astrometrics_history_get",
        app._api_astrometrics_history_get,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/update-field",
        "api_astrometrics_update_field",
        app._api_astrometrics_update_field,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/upload-yaml",
        "api_astrometrics_upload_yaml",
        app._api_astrometrics_upload_yaml,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/status",
        "api_astrometrics_status",
        app._api_astrometrics_status,
    )
    app.add_url_rule(
        "/api/astrometrics/verify",
        "api_astrometrics_verify",
        app._api_astrometrics_verify,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/astrometrics/sed",
        "api_astrometrics_sed",
        app._api_astrometrics_sed,
    )
    app.add_url_rule(
        "/api/astrometrics/hr-diagram",
        "api_astrometrics_hr",
        app._api_astrometrics_hr,
    )
    app.add_url_rule(
        "/api/astrometrics/resolve-online-by-name",
        "api_astrometrics_resolve_online_by_name",
        app._api_astrometrics_resolve_online_by_name,
    )
    app.add_url_rule(
        "/api/astrometrics/resolve-online-by-coords",
        "api_astrometrics_resolve_online_by_coords",
        app._api_astrometrics_resolve_online_by_coords,
    )
    app.add_url_rule(
        "/api/issues/list",
        "api_issues_list",
        app._api_issues_list,
    )
    app.add_url_rule(
        "/api/issues/create",
        "api_issues_create",
        app._api_issues_create,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/issues/update",
        "api_issues_update",
        app._api_issues_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/issues/users",
        "api_issues_users",
        app._api_issues_users,
    )
    app.add_url_rule(
        "/api/issues/delete",
        "api_issues_delete",
        app._api_issues_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/issues/edit",
        "api_issues_edit",
        app._api_issues_edit,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/known-errors/list",
        "api_known_errors_list",
        app._api_known_errors_list,
    )
    app.add_url_rule(
        "/api/known-errors/create",
        "api_known_errors_create",
        app._api_known_errors_create,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/known-errors/update",
        "api_known_errors_update",
        app._api_known_errors_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/known-errors/delete",
        "api_known_errors_delete",
        app._api_known_errors_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/meta",
        "api_schedule_meta",
        app._api_schedule_meta,
    )
    app.add_url_rule(
        "/api/monitor-schedule/entries/list",
        "api_schedule_entries_list",
        app._api_schedule_entries_list,
    )
    app.add_url_rule(
        "/api/monitor-schedule/entries/add",
        "api_schedule_entries_add",
        app._api_schedule_entries_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/entries/edit",
        "api_schedule_entries_edit",
        app._api_schedule_entries_edit,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/entries/delete",
        "api_schedule_entries_delete",
        app._api_schedule_entries_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/link-user-calendar",
        "api_schedule_link_user_calendar",
        app._api_schedule_link_user_calendar,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/tasks/upsert",
        "api_schedule_tasks_upsert",
        app._api_schedule_tasks_upsert,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/tasks/rename",
        "api_schedule_tasks_rename",
        app._api_schedule_tasks_rename,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/tasks/set-active",
        "api_schedule_tasks_set_active",
        app._api_schedule_tasks_set_active,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/calendar/week",
        "api_schedule_calendar_week",
        app._api_schedule_calendar_week,
    )
    app.add_url_rule(
        "/api/monitor-schedule/calendar/month",
        "api_schedule_calendar_month",
        app._api_schedule_calendar_month,
    )
    app.add_url_rule(
        "/api/monitor-schedule/calendar/weeks",
        "api_schedule_calendar_weeks",
        app._api_schedule_calendar_weeks,
    )
    app.add_url_rule(
        "/api/monitor-schedule/stats",
        "api_schedule_stats",
        app._api_schedule_stats,
    )
    app.add_url_rule(
        "/api/monitor-schedule/stats/visibility-set",
        "api_schedule_stats_visibility_set",
        app._api_schedule_stats_visibility_set,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/instrument-settings/set",
        "api_schedule_instrument_setting_set",
        app._api_schedule_instrument_setting_set,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor-schedule/entries/bulk-add",
        "api_schedule_entries_bulk_add",
        app._api_schedule_entries_bulk_add,
        methods=["POST"],
    )
    # ---------------------------------------------------------------
    # Notifications + messages + users directory
    # ---------------------------------------------------------------
    app.add_url_rule(
        "/api/notifications/list",
        "api_notifications_list",
        app._api_notifications_list,
    )
    app.add_url_rule(
        "/api/notifications/unread-count",
        "api_notifications_unread_count",
        app._api_notifications_unread_count,
    )
    app.add_url_rule(
        "/api/notifications/mark-read",
        "api_notifications_mark_read",
        app._api_notifications_mark_read,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/notifications/dismiss",
        "api_notifications_dismiss",
        app._api_notifications_dismiss,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/notifications/prefs",
        "api_notification_prefs_get",
        app._api_notification_prefs_get,
    )
    app.add_url_rule(
        "/api/notifications/prefs/save",
        "api_notification_prefs_save",
        app._api_notification_prefs_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/list",
        "api_messages_list",
        app._api_messages_list,
    )
    app.add_url_rule(
        "/api/messages/send",
        "api_messages_send",
        app._api_messages_send,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/<mid>",
        "api_messages_get",
        app._api_messages_get,
    )
    app.add_url_rule(
        "/api/messages/<mid>/delete",
        "api_messages_delete",
        app._api_messages_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/<mid>/mark-unread",
        "api_messages_mark_unread",
        app._api_messages_mark_unread,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/mark-all-read",
        "api_messages_mark_all_read",
        app._api_messages_mark_all_read,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/delete-all",
        "api_messages_delete_all",
        app._api_messages_delete_all,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/messages/<mid>/flag-as-issue",
        "api_messages_flag_as_issue",
        app._api_messages_flag_as_issue,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/users/directory",
        "api_users_directory",
        app._api_users_directory,
    )
    # User-portal pages for the new features
    app.add_url_rule(
        "/user_portal/users",
        "user_portal_users_view",
        app._user_portal_users_view,
    )
    app.add_url_rule(
        "/user_portal/users/<username>",
        "user_portal_user_card_view",
        app._user_portal_user_card_view,
    )
    app.add_url_rule(
        "/user_portal/messages",
        "user_portal_messages_view",
        app._user_portal_messages_view,
    )
    app.add_url_rule(
        "/user_portal/notifications",
        "user_portal_notifications_view",
        app._user_portal_notifications_view,
    )
    app.add_url_rule(
        "/monitor_portal/become_monitor",
        "become_monitor_view",
        app._become_monitor_view,
    )
    app.add_url_rule(
        "/monitor_portal",
        "monitor_portal_index_view",
        app._monitor_portal_index_view,
    )
    app.add_url_rule(
        "/monitor_portal/issues",
        "monitor_issues_view",
        app._monitor_issues_view,
    )
    app.add_url_rule(
        "/monitor_portal/known_errors",
        "monitor_known_errors_view",
        app._monitor_known_errors_view,
    )
    app.add_url_rule(
        "/monitor_portal/status",
        "monitor_status_view",
        app._monitor_status_view,
    )
    app.add_url_rule(
        '/monitor_portal/status/alliance',
        'monitor_status_alliance_view',
        app._monitor_status_alliance_view,
    )
    app.add_url_rule(
        '/monitor_portal/status/canfar',
        'monitor_status_canfar_view',
        app._monitor_status_canfar_view,
    )
    app.add_url_rule(
        "/monitor_portal/schedule",
        "monitor_schedule_view",
        app._monitor_schedule_view,
    )
    app.add_url_rule(
        "/monitor_portal/awards",
        "monitor_awards_view",
        app._monitor_awards_view,
    )
    app.add_url_rule(
        "/monitor_portal/proc_logs",
        "monitor_processing_logs_view",
        app._monitor_processing_logs_view,
    )
    app.add_url_rule(
        "/monitor_portal/proc_logs/<profile_id>",
        "monitor_processing_logs_profile_view",
        app._monitor_processing_logs_profile_view,
    )
    app.add_url_rule(
        "/monitor_portal/proc_logs/<profile_id>/<pid>",
        "monitor_processing_logs_pid_view",
        app._monitor_processing_logs_pid_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks",
        "monitor_apero_checks_view",
        app._monitor_apero_checks_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks/<profile_id>",
        "monitor_apero_checks_profile_view",
        app._monitor_apero_checks_profile_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks/<profile_id>/<obsdir>",
        "monitor_apero_checks_obsdir_view",
        app._monitor_apero_checks_obsdir_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks/<profile_id>/<obsdir>/check/<check_key>",
        "monitor_apero_checks_check_view",
        app._monitor_apero_checks_check_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks/<profile_id>/queue",
        "monitor_apero_checks_queue_view",
        app._monitor_apero_checks_queue_view,
    )
    app.add_url_rule(
        "/monitor_portal/apero_checks/<profile_id>/stats",
        "monitor_apero_checks_stats_view",
        app._monitor_apero_checks_stats_view,
    )
    app.add_url_rule(
        "/api/monitor/apero-checks/<profile_id>/stats",
        "api_apero_checks_stats",
        app._api_apero_checks_stats,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs",
        "api_processing_logs",
        app._api_processing_logs,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/pid",
        "api_processing_logs_pid",
        app._api_processing_logs_pid,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/logfile",
        "api_processing_log_file",
        app._api_processing_log_file,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/fail-report",
        "api_processing_logs_fail_report",
        app._api_processing_logs_fail_report,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/fail-report-info",
        "api_processing_logs_fail_report_info",
        app._api_processing_logs_fail_report_info,
        methods=["GET"],
    )
    app.add_url_rule(
        "/monitor_portal/proc_logs_report/<token>",
        "monitor_processing_logs_report_download",
        app._api_processing_logs_report_download,
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/filters/list",
        "api_processing_logs_filters_list",
        app._api_processing_logs_filters_list,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/filters/save",
        "api_processing_logs_filters_save",
        app._api_processing_logs_filters_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/filters/delete",
        "api_processing_logs_filters_delete",
        app._api_processing_logs_filters_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/processing-logs/pid/export",
        "api_processing_logs_pid_export",
        app._api_processing_logs_pid_export,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/apero-checks/update-failure",
        "api_apero_checks_update_failure",
        app._api_apero_checks_update_failure,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/apero-checks/create-issue",
        "api_apero_checks_create_issue",
        app._api_apero_checks_create_issue,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/monitor/apero-checks/config-save",
        "api_apero_checks_config_save",
        app._api_apero_checks_config_save,
        methods=["POST"],
    )
    app.add_url_rule(
        '/api/browse-dirs',
        'api_apero_checks_browse_dirs',
        app._api_apero_checks_browse_dirs,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/<profile_id>/page',
        'api_apero_checks_profile_page',
        app._api_apero_checks_profile_page,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/admin/apero-checks/<profile_id>/obsdirs',
        'api_apero_checks_list_obsdirs',
        app._api_apero_checks_list_obsdirs,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/policy-sections',
        'api_apero_checks_policy_sections',
        app._api_apero_checks_policy_sections,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/view-yaml',
        'api_apero_checks_view_yaml',
        app._api_apero_checks_view_yaml,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/validate-obsdir',
        'api_apero_checks_validate_obsdir',
        app._api_apero_checks_validate_obsdir,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/rerun-night',
        'api_apero_checks_rerun_night',
        app._api_apero_checks_rerun_night,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/rerun-check',
        'api_apero_checks_rerun_single_check',
        app._api_apero_checks_rerun_single_check,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/advanced-run',
        'api_apero_checks_advanced_run',
        app._api_apero_checks_advanced_run,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/clean-reset-profile',
        'api_apero_checks_clean_reset_profile',
        app._api_apero_checks_clean_reset_profile,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/delete-obsdir',
        'api_apero_checks_delete_obsdir',
        app._api_apero_checks_delete_obsdir,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/exclude-obsdir',
        'api_apero_checks_exclude_obsdir',
        app._api_apero_checks_exclude_obsdir,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/admin/apero-checks/excluded-obsdirs',
        'api_apero_checks_list_excluded_obsdirs',
        app._api_apero_checks_list_excluded_obsdirs,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/admin/apero-checks/excluded-obsdirs/remove',
        'api_apero_checks_remove_excluded_obsdir',
        app._api_apero_checks_remove_excluded_obsdir,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/delete-test-from-yamls',
        'api_apero_checks_delete_test_from_yamls',
        app._api_apero_checks_delete_test_from_yamls,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/check-results',
        'api_apero_checks_check_results',
        app._api_apero_checks_check_results,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/admin/apero-checks/check-info-async',
        'api_apero_checks_check_info_async',
        app._api_apero_checks_check_info_async,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/admin/apero-checks/policy-build-status',
        'api_apero_checks_policy_build_status',
        app._api_apero_checks_policy_build_status,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/<profile_id>/queue-status',
        'api_apero_checks_queue_status',
        app._api_apero_checks_queue_status,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/<profile_id>/queue-cancel-task',
        'api_apero_checks_queue_cancel_task',
        app._api_apero_checks_queue_cancel_task,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/<profile_id>/queue-kill-profile',
        'api_apero_checks_queue_kill_profile',
        app._api_apero_checks_queue_kill_profile,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/monitor/apero-checks/<profile_id>/queue-clear-history',
        'api_apero_checks_queue_clear_history',
        app._api_apero_checks_queue_clear_history,
        methods=['POST'],
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/observation-table",
        "ri_observation_table",
        app._ri_object_table_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/query-db",
        "ri_query_db",
        app._ri_query_db_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/fav-objects",
        "ri_fav_objects",
        app._ri_favourites_objects_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/favourites-objects",
        "ri_favourites_objects_legacy",
        app._ri_favourites_objects_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/object-groups",
        "ri_object_groups",
        app._ri_object_groups_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/object-groups/<path:group_name>"
        "/summary-table",
        "ri_object_group_summary",
        app._ri_object_group_summary_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/fav-objects/<path:section_name>"
        "/summary-table",
        "ri_favourites_summary",
        app._ri_favourites_summary_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/qc-graphs",
        "ri_qc_graphs",
        app._ri_qc_graphs_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/qc-graphs/max"
        "/<section>/<metric_key>/<view_key>",
        "ri_qc_graphs_max",
        app._ri_qc_graphs_max_view,
    )
    app.add_url_rule(
        "/api/data-portal/query-db/schema",
        "api_query_db_schema",
        app._api_query_db_schema,
    )
    app.add_url_rule(
        "/api/data-portal/query-db/run",
        "api_query_db_run",
        app._api_query_db_run,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/query-db/count",
        "api_query_db_count",
        app._api_query_db_count,
        methods=["POST"],
    )

    # Download basket page + APIs (must be before /<path:objname> catch-all)
    app.add_url_rule(
        "/data_portal/<profile_id>/basket", "ri_basket", app._ri_basket_view
    )
    app.add_url_rule(
        "/api/data-portal/basket", "api_basket_get", app._api_basket_get
    )
    app.add_url_rule(
        "/api/data-portal/basket/summary",
        "api_basket_summary",
        app._api_basket_summary,
    )
    app.add_url_rule(
        "/api/data-portal/basket/add",
        "api_basket_add",
        app._api_basket_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/remove",
        "api_basket_remove",
        app._api_basket_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/clear",
        "api_basket_clear",
        app._api_basket_clear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/compile",
        "api_basket_compile",
        app._api_basket_compile,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/compile-status/<job_id>",
        "api_basket_compile_status",
        app._api_basket_compile_status,
    )
    app.add_url_rule(
        "/api/data-portal/basket/download/<job_id>/<int:chunk_idx>",
        "api_basket_download",
        app._api_basket_download,
    )
    app.add_url_rule(
        "/api/data-portal/basket/jobs", "api_basket_jobs", app._api_basket_jobs
    )
    app.add_url_rule(
        "/api/data-portal/basket/jobs/extend",
        "api_basket_jobs_extend",
        app._api_basket_jobs_extend,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/jobs/expiry",
        "api_basket_jobs_expiry",
        app._api_basket_jobs_expiry,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/jobs/remove",
        "api_basket_jobs_remove",
        app._api_basket_jobs_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/jobs/clear",
        "api_basket_jobs_clear",
        app._api_basket_jobs_clear,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/add-from-ftable",
        "api_basket_add_from_ftable",
        app._api_basket_add_from_ftable,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/share-token",
        "api_basket_share_token",
        app._api_basket_share_token,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/basket/share-email",
        "api_basket_share_email",
        app._api_basket_share_email,
        methods=["POST"],
    )
    app.add_url_rule("/share/<token>", "share_landing", app._share_landing)
    app.add_url_rule(
        "/share/<token>/file/<int:chunk_idx>",
        "share_download",
        app._share_download,
    )
    app.add_url_rule(
        "/api/data-portal/file-browser",
        "api_file_browser",
        app._api_file_browser,
    )
    app.add_url_rule(
        '/api/data-portal/file-header',
        'api_file_header',
        app._api_file_header,
    )
    app.add_url_rule(
        '/api/data-portal/file-header-download',
        'api_file_header_download',
        app._api_file_header_download,
    )

    app.add_url_rule(
        "/data_portal/<profile_id>/object-plot-max/<objname>/<plot_key>",
        "ri_object_plot_max",
        app._ri_object_plot_max_view,
    )
    app.add_url_rule(
        "/data_portal/<profile_id>/<path:objname>",
        "ri_object_page",
        app._ri_object_page_view,
    )
    app.add_url_rule(
        "/api/data-portal/object-page", "api_object_page", app._api_object_page
    )
    app.add_url_rule(
        "/api/data-portal/object-rejection-issue",
        "api_object_rejection_issue",
        app._api_object_rejection_issue,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-plots",
        "api_object_plots",
        app._api_object_plots,
    )
    app.add_url_rule(
        "/api/data-portal/object-download",
        "api_object_download",
        app._api_object_download,
    )
    app.add_url_rule(
        "/api/data-portal/object-lbl-plots",
        "api_object_lbl_plots",
        app._api_object_lbl_plots,
    )
    app.add_url_rule(
        "/api/user/favourite-objects/get",
        "api_user_favourite_objects_get",
        app._api_user_favourite_objects_get,
    )
    app.add_url_rule(
        "/api/user/favourite-objects/toggle",
        "api_user_favourite_objects_toggle",
        app._api_user_favourite_objects_toggle,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/remove",
        "api_user_favourite_objects_remove",
        app._api_user_favourite_objects_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/reorder",
        "api_user_favourite_objects_reorder",
        app._api_user_favourite_objects_reorder,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/last-opened",
        "api_user_favourite_objects_last_opened",
        app._api_user_favourite_objects_last_opened,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/sections/save",
        "api_user_favourite_objects_sections_save",
        app._api_user_favourite_objects_sections_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/sections/rename",
        "api_user_favourite_objects_sections_rename",
        app._api_user_favourite_objects_sections_rename,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/sections/delete",
        "api_user_favourite_objects_sections_delete",
        app._api_user_favourite_objects_sections_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/meta/save",
        "api_user_favourite_objects_meta_save",
        app._api_user_favourite_objects_meta_save,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/add",
        "api_user_favourite_objects_add",
        app._api_user_favourite_objects_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/favourite-objects/add-bulk",
        "api_user_favourite_objects_add_bulk",
        app._api_user_favourite_objects_add_bulk,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/finder-chart",
        "api_finder_chart",
        app._api_finder_chart,
    )
    app.add_url_rule(
        "/api/data-portal/finder-chart-stream",
        "api_finder_chart_stream",
        app._api_finder_chart_stream,
    )
    app.add_url_rule(
        "/api/data-portal/tess-rotation",
        "api_tess_rotation",
        app._api_tess_rotation,
    )
    app.add_url_rule(
        "/api/data-portal/tess-rotation-lc",
        "api_tess_rotation_lc",
        app._api_tess_rotation_lc,
    )
    app.add_url_rule(
        "/api/data-portal/tess-rotation-stream",
        "api_tess_rotation_stream",
        app._api_tess_rotation_stream,
    )
    app.add_url_rule(
        "/api/data-portal/tess-rotation-data",
        "api_tess_rotation_data",
        app._api_tess_rotation_data,
    )

    # Object comments API routes
    app.add_url_rule(
        "/api/data-portal/object-comments/list",
        "api_object_comments_list",
        app._api_object_comments_list,
    )
    app.add_url_rule(
        "/api/data-portal/object-comments/add",
        "api_object_comments_add",
        app._api_object_comments_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-comments/edit",
        "api_object_comments_edit",
        app._api_object_comments_edit,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-comments/delete",
        "api_object_comments_delete",
        app._api_object_comments_delete,
        methods=["POST"],
    )

    # Object groups API routes
    app.add_url_rule(
        "/api/data-portal/object-groups/list",
        "api_object_groups_list",
        app._api_object_groups_list,
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/for-object",
        "api_object_groups_for_object",
        app._api_object_groups_for_object,
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/objects",
        "api_object_groups_objects",
        app._api_object_groups_objects,
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/summary-config",
        "api_object_groups_summary_config",
        app._api_object_groups_summary_config,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/summary-table",
        "api_object_groups_summary_table",
        app._api_object_groups_summary_table,
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/summary-export",
        "api_object_groups_summary_export",
        app._api_object_groups_summary_export,
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/summary-custom-test",
        "api_object_groups_summary_custom_test",
        app._api_object_groups_summary_custom_test,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/create",
        "api_object_groups_create",
        app._api_object_groups_create,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/delete",
        "api_object_groups_delete",
        app._api_object_groups_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/rename",
        "api_object_groups_rename",
        app._api_object_groups_rename,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/add-object",
        "api_object_groups_add_object",
        app._api_object_groups_add_object,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/add-objects-bulk",
        "api_object_groups_add_objects_bulk",
        app._api_object_groups_add_objects_bulk,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups"
        "/add-objects-json",
        "api_object_groups_add_objects_json",
        app._api_object_groups_add_objects_json,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/data-portal/object-groups/remove-object",
        "api_object_groups_remove_object",
        app._api_object_groups_remove_object,
        methods=["POST"],
    )
    app.add_url_rule(
        '/api/admin/allowed-python-expressions',
        'api_object_groups_allowed_expressions',
        app._api_object_groups_allowed_expressions,
        methods=['GET', 'POST'],
    )
    app.add_url_rule(
        '/api/admin/custom-columns',
        'api_object_groups_admin_custom_columns',
        app._api_object_groups_admin_custom_columns,
        methods=['GET', 'POST'],
    )
    app.add_url_rule(
        '/api/admin/custom-columns/test',
        'api_object_groups_admin_custom_test',
        app._api_object_groups_admin_custom_test,
        methods=['POST'],
    )
    app.add_url_rule(
        '/api/clocks',
        'api_clocks_get',
        app._api_clocks_get,
        methods=['GET'],
    )
    app.add_url_rule(
        '/api/admin/clocks',
        'api_admin_clocks',
        app._api_admin_clocks,
        methods=['GET', 'POST'],
    )

    app.add_url_rule(
        "/api/data-portal/debug-plots", "api_debug_plots", app._api_debug_plots
    )
    app.add_url_rule(
        "/api/data-portal/tcorr-map-generate",
        "api_tcorr_map_generate",
        app._api_tcorr_map_generate,
    )
    app.add_url_rule(
        "/api/data-portal/filename-plot",
        "api_filename_plot",
        app._api_filename_plot,
    )
    app.add_url_rule(
        "/api/data-portal/obs-table", "api_obs_table", app._api_obs_table
    )
    app.add_url_rule(
        "/api/admin/instruments/groups/create",
        "api_manage_instruments_groups_create",
        app._api_manage_instruments_groups_create,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/instruments/groups/delete",
        "api_manage_instruments_groups_delete",
        app._api_manage_instruments_groups_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/instruments/add",
        "api_manage_instruments_add",
        app._api_manage_instruments_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/instruments/remove",
        "api_manage_instruments_remove",
        app._api_manage_instruments_remove,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/instruments/rename",
        "api_manage_instruments_rename",
        app._api_manage_instruments_rename,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/instruments/yaml/get",
        "api_manage_instruments_yaml_get",
        app._api_manage_instruments_yaml_get,
    )
    app.add_url_rule(
        "/api/admin/instruments/yaml/save",
        "api_manage_instruments_yaml_save",
        app._api_manage_instruments_yaml_save,
        methods=["POST"],
    )

    # Vault — Admin routes
    app.add_url_rule(
        "/api/admin/vault/list",
        "api_admin_vault_list",
        app._api_admin_vault_list,
    )
    app.add_url_rule(
        "/api/admin/vault/get",
        "api_admin_vault_get",
        app._api_admin_vault_get,
    )
    app.add_url_rule(
        "/api/admin/vault/add",
        "api_admin_vault_add",
        app._api_admin_vault_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/vault/update",
        "api_admin_vault_update",
        app._api_admin_vault_update,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/vault/delete",
        "api_admin_vault_delete",
        app._api_admin_vault_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/vault/export",
        "api_admin_vault_export",
        app._api_admin_vault_export,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/vault/import",
        "api_admin_vault_import",
        app._api_admin_vault_import,
        methods=["POST"],
    )

    # Upload management — Admin routes
    app.add_url_rule(
        "/api/admin/uploads/config",
        "api_admin_uploads_config_get",
        app._api_admin_uploads_config_get,
    )
    app.add_url_rule(
        "/api/admin/uploads/dir/add",
        "api_admin_uploads_dir_add",
        app._api_admin_uploads_dir_add,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/uploads/dir/edit",
        "api_admin_uploads_dir_edit",
        app._api_admin_uploads_dir_edit,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/uploads/dir/delete",
        "api_admin_uploads_dir_delete",
        app._api_admin_uploads_dir_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/admin/uploads/quota",
        "api_admin_uploads_quota_get",
        app._api_admin_uploads_quota_get,
    )

    # Upload management — User routes
    app.add_url_rule(
        "/api/user/uploads/list",
        "api_user_uploads_list",
        app._api_user_uploads_list,
    )
    app.add_url_rule(
        "/api/user/uploads/upload",
        "api_user_uploads_upload",
        app._api_user_uploads_upload,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/uploads/delete",
        "api_user_uploads_delete",
        app._api_user_uploads_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/user/uploads/share",
        "api_user_uploads_share",
        app._api_user_uploads_share,
        methods=["POST"],
    )

    # Shared file download
    app.add_url_rule(
        "/uploads/share/<token>",
        "uploads_share_download",
        app._uploads_share_download,
    )
