# define detector type (default = H4RG)
type = H4RG

# define whether we run the comparison with old drs (default = False)
comparison = False

# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# Calibrations
# run000 = ['cal_preprocess_spirou', '18BQ01-Aug05', '*.fits']
run001 = ['cal_DARK_spirou', '18BQ01-Aug05', 'dark_dark_P5_003d_pp.fits']
run002 = ['cal_BADPIX_spirou', '18BQ01-Aug05', '2295524f_pp.fits', 'dark_dark_P5_003d_pp.fits']
run003a = ['cal_loc_RAW_spirou', '18BQ01-Aug05', '2295510f_pp.fits', '2295511f_pp.fits', '2295512f_pp.fits', '2295513f_pp.fits', '2295514f_pp.fits']
run003b = ['cal_loc_RAW_spirou', '18BQ01-Aug05', '2295515f_pp.fits', '2295516f_pp.fits', '2295517f_pp.fits', '2295518f_pp.fits', '2295519f_pp.fits']
run005 = ['cal_SLIT_spirou', '18BQ01-Aug05', '2295525a_pp.fits']
run006 = ['cal_FF_RAW_spirou', '18BQ01-Aug05', '2295520f_pp.fits', '2295521f_pp.fits', '2295522f_pp.fits', '2295523f_pp.fits', '2295524f_pp.fits']

# Extract the FPs
run007a = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295525f_pp.fits']
run007b = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295526f_pp.fits']
run007c = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295527f_pp.fits']
run007d = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295528f_pp.fits']
run007e = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295529f_pp.fits']

# Extract the science
run007f = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295545o_pp.fits']
run007g = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295546o_pp.fits']
run007h = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295547o_pp.fits']
run007i = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295548o_pp.fits']
run007j = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295549o_pp.fits']
run007k = ['cal_extract_RAW_spirou', '18BQ01-Aug05', '2295550o_pp.fits']

# Run drift analysis
run010a = ['cal_DRIFT_E2DS_spirou', '18BQ01-Aug05', '2295525a_pp_e2ds_AB.fits']
run010b = ['cal_DRIFTPEAK_E2DS_spirou', '18BQ01-Aug05', '2295525a_pp_e2ds_AB.fits']

#run008 = ['cal_HC_E2DS_spirou', '18BQ01-Aug05', '']
#run009 = ['cal_WAVE_E2DS_spirou', '18BQ01-Aug05', '2295525a_pp_e2ds_AB.fits', '']

#run011 = ['cal_CCF_E2DS_spirou', '18BQ01-Aug05', '????', 'UrNe.mas', 0, 10, 0.1]
run012 = ['cal_exposure_meter', '18BQ01-Aug05', '2295519f_pp.fits']
run013 = ['off_listing_RAW_spirou', '18BQ01-Aug05']
run014 = ['off_listing_REDUC_spirou', '18BQ01-Aug05']