# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# pre-processing
run000a = ['cal_preprocess_spirou', 'TEST2/20180731', '*.fits']
run000b = ['cal_preprocess_spirou', 'TEST2/20180801', '*.fits']
run000c = ['cal_preprocess_spirou', 'TEST2/20180802', '*.fits']
run000d = ['cal_preprocess_spirou', 'TEST2/20180803', '*.fits']
run000e = ['cal_preprocess_spirou', 'TEST2/20180804', '*.fits']
run000f = ['cal_preprocess_spirou', 'TEST2/20180805', '*.fits']

# Calibrations
# run001 = ['cal_DARK_spirou', 'TEST1/20180805', 'dark_dark_P5_003d_pp.fits']
# run002 = ['cal_BADPIX_spirou', 'TEST1/20180805', '2295524f_pp.fits', 'dark_dark_P5_003d_pp.fits']
# run003a = ['cal_loc_RAW_spirou', 'TEST1/20180805', '2295510f_pp.fits', '2295511f_pp.fits', '2295512f_pp.fits', '2295513f_pp.fits', '2295514f_pp.fits']
# run003b = ['cal_loc_RAW_spirou', 'TEST1/20180805', '2295515f_pp.fits', '2295516f_pp.fits', '2295517f_pp.fits', '2295518f_pp.fits', '2295519f_pp.fits']
# run005 = ['cal_SLIT_spirou', 'TEST1/20180805', '2295525a_pp.fits']
# run006 = ['cal_FF_RAW_spirou', 'TEST1/20180805', '2295520f_pp.fits', '2295521f_pp.fits', '2295522f_pp.fits', '2295523f_pp.fits', '2295524f_pp.fits']

# Extract the HC's/FP's
# run007a = ['cal_extract_RAW_spirou', 'TEST1/20180805', '2295525a_pp.fits']
# run007b = ['cal_extract_RAW_spirou', 'TEST1/20180805', '20180817_hc1_hc1_seq_001c_pp.fits']

# Run Wave solution analysis
# run008 = ['cal_HC_E2DS_spirou', 'TEST1/20180805', '20180817_hc1_hc1_seq_001c_pp_e2ds_AB.fits']
# run009 = ['cal_WAVE_E2DS_spirou', 'TEST1/20180805', '2295525a_pp_e2ds_AB.fits', '20180817_hc1_hc1_seq_001c_pp_e2ds_AB.fits']

# Extract the tellurics
run010a = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294972o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294973o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295080o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295118o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295124o_pp.fits']
run010f = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295126o_pp.fits']
run010g = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295200o_pp.fits']
run010h = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295243o_pp.fits']
run010i = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295248o_pp.fits']
run010j = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295265o_pp.fits']
run010k = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295266o_pp.fits']
run010l = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295353o_pp.fits']
run010m = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295358o_pp.fits']
run010n = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295412o_pp.fits']
run010o = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295470o_pp.fits']
run010p = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295479o_pp.fits']
run010q = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295480o_pp.fits']
run010r = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295485o_pp.fits']
run010s = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295486o_pp.fits']
run010t = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295487o_pp.fits']
run010u = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295492o_pp.fits']
run010v = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295506o_pp.fits']
run010w = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295545o_pp.fits']
run010x = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295546o_pp.fits']
run010y = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295547o_pp.fits']

# Run Make telluric recipes
run11a = ['obj_mk_tellu', 'TEST2/20180731', '2294972o_pp_e2dsff_AB.fits']
run11b = ['obj_mk_tellu', 'TEST2/20180731', '2294973o_pp_e2dsff_AB.fits']
run11c = ['obj_mk_tellu', 'TEST2/20180801', '2295080o_pp_e2dsff_AB.fits']
run11d = ['obj_mk_tellu', 'TEST2/20180801', '2295118o_pp_e2dsff_AB.fits']
run11e = ['obj_mk_tellu', 'TEST2/20180801', '2295124o_pp_e2dsff_AB.fits']
run11f = ['obj_mk_tellu', 'TEST2/20180801', '2295126o_pp_e2dsff_AB.fits']
run11g = ['obj_mk_tellu', 'TEST2/20180802', '2295200o_pp_e2dsff_AB.fits']
run11h = ['obj_mk_tellu', 'TEST2/20180802', '2295243o_pp_e2dsff_AB.fits']
run11i = ['obj_mk_tellu', 'TEST2/20180802', '2295248o_pp_e2dsff_AB.fits']
run11j = ['obj_mk_tellu', 'TEST2/20180802', '2295265o_pp_e2dsff_AB.fits']
run11k = ['obj_mk_tellu', 'TEST2/20180802', '2295266o_pp_e2dsff_AB.fits']
run11l = ['obj_mk_tellu', 'TEST2/20180803', '2295353o_pp_e2dsff_AB.fits']
run11m = ['obj_mk_tellu', 'TEST2/20180803', '2295358o_pp_e2dsff_AB.fits']
run11n = ['obj_mk_tellu', 'TEST2/20180804', '2295412o_pp_e2dsff_AB.fits']
run11o = ['obj_mk_tellu', 'TEST2/20180804', '2295470o_pp_e2dsff_AB.fits']
run11p = ['obj_mk_tellu', 'TEST2/20180804', '2295479o_pp_e2dsff_AB.fits']
run11q = ['obj_mk_tellu', 'TEST2/20180804', '2295480o_pp_e2dsff_AB.fits']
run11r = ['obj_mk_tellu', 'TEST2/20180804', '2295485o_pp_e2dsff_AB.fits']
run11s = ['obj_mk_tellu', 'TEST2/20180804', '2295486o_pp_e2dsff_AB.fits']
run11t = ['obj_mk_tellu', 'TEST2/20180804', '2295487o_pp_e2dsff_AB.fits']
run11u = ['obj_mk_tellu', 'TEST2/20180804', '2295492o_pp_e2dsff_AB.fits']
run11v = ['obj_mk_tellu', 'TEST2/20180804', '2295506o_pp_e2dsff_AB.fits']

# Run Fit telluric recipes (on telluric stars --> Should be science target!)
run12a = ['obj_fit_tellu', 'TEST2/20180802', '2295266o_pp_e2dsff_AB.fits']
run12b = ['obj_fit_tellu', 'TEST2/20180805', '2295545o_pp_e2dsff_AB.fits']
run12c = ['obj_fit_tellu', 'TEST2/20180805', '2295546o_pp_e2dsff_AB.fits']
run12d = ['obj_fit_tellu', 'TEST2/20180805', '2295547o_pp_e2dsff_AB.fits']
