# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# requires Cal_Test.run to be run first

# pre-processing
run000a = ['cal_preprocess_spirou', 'TEST2/20180731', '*.fits']
run000b = ['cal_preprocess_spirou', 'TEST2/20180801', '*.fits']
run000c = ['cal_preprocess_spirou', 'TEST2/20180802', '*.fits']
run000d = ['cal_preprocess_spirou', 'TEST2/20180803', '*.fits']
run000e = ['cal_preprocess_spirou', 'TEST2/20180804', '*.fits']
run000f = ['cal_preprocess_spirou', 'TEST2/20180805', '*.fits']

# Extract the tellurics
run009a = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294972o_pp.fits']
run009b = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294973o_pp.fits']
run009c = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295080o_pp.fits']
run009d = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295118o_pp.fits']
run009e = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295124o_pp.fits']
run009f = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295126o_pp.fits']
run009g = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295200o_pp.fits']
run009h = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295243o_pp.fits']
run009i = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295248o_pp.fits']
run009j = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295265o_pp.fits']
run009k = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295266o_pp.fits']
run009l = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295353o_pp.fits']
run009m = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295358o_pp.fits']
run009n = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295412o_pp.fits']
run009o = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295470o_pp.fits']
run009p = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295479o_pp.fits']
run009q = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295480o_pp.fits']
run009r = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295485o_pp.fits']
run009s = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295486o_pp.fits']
run009t = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295487o_pp.fits']
run009u = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295492o_pp.fits']
run009v = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295506o_pp.fits']

# Extract Gl699
run010a = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295545o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295546o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295547o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295548o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295549o_pp.fits']
run010f = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295550o_pp.fits']

# Run Make telluric recipes
run011a = ['obj_mk_tellu', 'TEST2/20180731', '2294972o_pp_e2dsff_AB.fits']
run011b = ['obj_mk_tellu', 'TEST2/20180731', '2294973o_pp_e2dsff_AB.fits']
run011c = ['obj_mk_tellu', 'TEST2/20180801', '2295080o_pp_e2dsff_AB.fits']
run011d = ['obj_mk_tellu', 'TEST2/20180801', '2295118o_pp_e2dsff_AB.fits']
run011e = ['obj_mk_tellu', 'TEST2/20180801', '2295124o_pp_e2dsff_AB.fits']
run011f = ['obj_mk_tellu', 'TEST2/20180801', '2295126o_pp_e2dsff_AB.fits']
run011g = ['obj_mk_tellu', 'TEST2/20180802', '2295200o_pp_e2dsff_AB.fits']
run011h = ['obj_mk_tellu', 'TEST2/20180802', '2295243o_pp_e2dsff_AB.fits']
run011i = ['obj_mk_tellu', 'TEST2/20180802', '2295248o_pp_e2dsff_AB.fits']
run011j = ['obj_mk_tellu', 'TEST2/20180802', '2295265o_pp_e2dsff_AB.fits']
run011k = ['obj_mk_tellu', 'TEST2/20180802', '2295266o_pp_e2dsff_AB.fits']
run011l = ['obj_mk_tellu', 'TEST2/20180803', '2295353o_pp_e2dsff_AB.fits']
run011m = ['obj_mk_tellu', 'TEST2/20180803', '2295358o_pp_e2dsff_AB.fits']
run011n = ['obj_mk_tellu', 'TEST2/20180804', '2295412o_pp_e2dsff_AB.fits']
run011o = ['obj_mk_tellu', 'TEST2/20180804', '2295470o_pp_e2dsff_AB.fits']
run011p = ['obj_mk_tellu', 'TEST2/20180804', '2295479o_pp_e2dsff_AB.fits']
run011q = ['obj_mk_tellu', 'TEST2/20180804', '2295480o_pp_e2dsff_AB.fits']
run011r = ['obj_mk_tellu', 'TEST2/20180804', '2295485o_pp_e2dsff_AB.fits']
run011s = ['obj_mk_tellu', 'TEST2/20180804', '2295486o_pp_e2dsff_AB.fits']
run011t = ['obj_mk_tellu', 'TEST2/20180804', '2295487o_pp_e2dsff_AB.fits']
run011u = ['obj_mk_tellu', 'TEST2/20180804', '2295492o_pp_e2dsff_AB.fits']
run011v = ['obj_mk_tellu', 'TEST2/20180804', '2295506o_pp_e2dsff_AB.fits']

# Run Fit telluric recipes
run012a = ['obj_fit_tellu', 'TEST2/20180805', '2295545o_pp_e2dsff_AB.fits']
run012b = ['obj_fit_tellu', 'TEST2/20180805', '2295546o_pp_e2dsff_AB.fits']
run012c = ['obj_fit_tellu', 'TEST2/20180805', '2295547o_pp_e2dsff_AB.fits']
run012d = ['obj_fit_tellu', 'TEST2/20180805', '2295548o_pp_e2dsff_AB.fits']
run012e = ['obj_fit_tellu', 'TEST2/20180805', '2295549o_pp_e2dsff_AB.fits']
run012e = ['obj_fit_tellu', 'TEST2/20180805', '2295550o_pp_e2dsff_AB.fits']

# Test cal_CCF
run013 = ['cal_CCF_E2DS_spirou', 'TEST2/20180802', '2295266o_pp_e2dsff_AB_tellu_corrected.fits', 'tellurique_test9.mas', 0, 100, 0.5]


