# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# pre-processing
# run000a = ['cal_preprocess_spirou', 'TEST1/20180805', '*.fits']
run000b = ['cal_preprocess_spirou', 'TEST2/20180823', '*.fits']
run000c = ['cal_preprocess_spirou', 'TEST2/20180824', '*.fits']
run000d = ['cal_preprocess_spirou', 'TEST2/20180825', '*.fits']

# Calibrations
# run001 = ['cal_DARK_spirou', 'TEST1/20180805', 'dark_dark_P5_003d_pp.fits']
# run002 = ['cal_BADPIX_spirou', 'TEST1/20180805', '2295524f_pp.fits', 'dark_dark_P5_003d_pp.fits']
# run003a = ['cal_loc_RAW_spirou', 'TEST1/20180805', '2295510f_pp.fits', '2295511f_pp.fits', '2295512f_pp.fits', '2295513f_pp.fits', '2295514f_pp.fits']
# run003b = ['cal_loc_RAW_spirou', 'TEST1/20180805', '2295515f_pp.fits', '2295516f_pp.fits', '2295517f_pp.fits', '2295518f_pp.fits', '2295519f_pp.fits']
# run005 = ['cal_SLIT_spirou', 'TEST1/20180805', '2295525a_pp.fits']
# run006 = ['cal_FF_RAW_spirou', 'TEST1/20180805', '2295520f_pp.fits', '2295521f_pp.fits', '2295522f_pp.fits', '2295523f_pp.fits', '2295524f_pp.fits']

# Extract the HC's/FP's
# run007a = ['cal_extract_RAW_spirou', 'TEST1/20180805', '2295525a_pp.fits']
# run007b = ['cal_extract_RAW_spirou', 'TEST1/20180805', '20180817_hc1_hc1_seq_001c_pp.fits']

# Run Wave solution analysis
# run008 = ['cal_HC_E2DS_spirou', 'TEST1/20180805', '20180817_hc1_hc1_seq_001c_pp_e2ds_AB.fits']
# run009 = ['cal_WAVE_E2DS_spirou', 'TEST1/20180805', '2295525a_pp_e2ds_AB.fits', '20180817_hc1_hc1_seq_001c_pp_e2ds_AB.fits']

# Extract the tellurics
run010a = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2278951o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2278952o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279005o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279006o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279007o_pp.fits']
run010f = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279008o_pp.fits']
run010g = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279009o_pp.fits']
run010h = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279010o_pp.fits']
run010i = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279017o_pp.fits']
run010j = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279018o_pp.fits']
run010k = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279019o_pp.fits']
run010l = ['cal_extract_RAW_spirou', 'TEST2/20180823', '2279020o_pp.fits']
run010m = ['cal_extract_RAW_spirou', 'TEST2/20180824', '2279104o_pp.fits']
run010n = ['cal_extract_RAW_spirou', 'TEST2/20180825', '2279197o_pp.fits']

# Run Make telluric recipes
run11a = ['obj_mk_tellu', 'TEST2/20180823', '2278951o_pp_e2dsff_AB.fits']
run11b = ['obj_mk_tellu', 'TEST2/20180823', '2278952o_pp_e2dsff_AB.fits']
run11c = ['obj_mk_tellu', 'TEST2/20180823', '2279005o_pp_e2dsff_AB.fits']
run11d = ['obj_mk_tellu', 'TEST2/20180823', '2279006o_pp_e2dsff_AB.fits']
run11e = ['obj_mk_tellu', 'TEST2/20180823', '2279007o_pp_e2dsff_AB.fits']
run11f = ['obj_mk_tellu', 'TEST2/20180823', '2279008o_pp_e2dsff_AB.fits']
run11g = ['obj_mk_tellu', 'TEST2/20180823', '2279009o_pp_e2dsff_AB.fits']
run11h = ['obj_mk_tellu', 'TEST2/20180823', '2279010o_pp_e2dsff_AB.fits']
run11i = ['obj_mk_tellu', 'TEST2/20180823', '2279017o_pp_e2dsff_AB.fits']
run11j = ['obj_mk_tellu', 'TEST2/20180823', '2279018o_pp_e2dsff_AB.fits']
run11k = ['obj_mk_tellu', 'TEST2/20180823', '2279019o_pp_e2dsff_AB.fits']
run11l = ['obj_mk_tellu', 'TEST2/20180823', '2279020o_pp_e2dsff_AB.fits']
run11m = ['obj_mk_tellu', 'TEST2/20180824', '2279104o_pp_e2dsff_AB.fits']
run11n = ['obj_mk_tellu', 'TEST2/20180825', '2279197o_pp_e2dsff_AB.fits']

# Run Fit telluric recipes (on telluric stars --> Should be science target!)
run12a = ['obj_fit_tellu', 'TEST2/20180823', '2278951o_pp_e2dsff_AB.fits']
run12b = ['obj_fit_tellu', 'TEST2/20180823', '2279005o_pp_e2dsff_AB.fits']

