# define detector type (default = H4RG)
type = H4RG

# define whether we run the comparison with old drs (default = False)
comparison = False

# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)
run008 = ['cal_HC_E2DS_spirou', 'AT5/20180409', 'hcone_hcone_001_pp_e2dsff_AB.fits']
run009a = ['cal_WAVE_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2dsff_AB.fits', 'hcone_hcone_001_pp_e2dsff_AB.fits', ]
# run009b = ['cal_WAVE_NEW_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2dsff_AB.fits', 'hcone_hcone_001_pp_e2dsff_AB.fits']