# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# Run Wave solution analysis
run008 = ['cal_HC_E2DS_EA_spirou', 'TEST3/20180526', '2279330c_pp_e2ds_AB.fits']
# run009 = ['cal_WAVE_E2DS_EA_spirou', 'TEST3/20180526', '2279327a_pp_e2ds_AB.fits', '2279330c_pp_e2ds_AB.fits']

# Extract the tellurics
run010a = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279383o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279384o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279385o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279386o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run010f = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279330c_pp.fits']

# Run Polar recipe
run011 = ['pol_spirou', 'TEST3/20180526', '2279383o_pp_e2dsff_A.fits', '2279383o_pp_e2dsff_B.fits', '2279384o_pp_e2dsff_A.fits', '2279384o_pp_e2dsff_B.fits', '2279385o_pp_e2dsff_A.fits', '2279385o_pp_e2dsff_B.fits', '2279386o_pp_e2dsff_A.fits', '2279386o_pp_e2dsff_B.fits']

