# define detector type (default = H4RG)
type = H4RG

# define whether we run the comparison with old drs (default = False)
comparison = False

# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)
run000 = ['obj_mk_tellu', 'tellu_e2ds', '2278951o_betSer_pp_e2dsff_AB.fits']
run001 = ['obj_mk_tellu', 'tellu_e2ds', '2278952o_betSer_pp_e2dsff_AB.fits']
run002 = ['obj_mk_tellu', 'tellu_e2ds', '2279005o_HR8489_pp_e2dsff_AB.fits']
run003 = ['obj_mk_tellu', 'tellu_e2ds', '2279006o_HR8489_pp_e2dsff_AB.fits']
run004 = ['obj_mk_tellu', 'tellu_e2ds', '2279007o_HR8489_pp_e2dsff_AB.fits']
run005 = ['obj_mk_tellu', 'tellu_e2ds', '2279008o_HR8489_pp_e2dsff_AB.fits']
run006 = ['obj_mk_tellu', 'tellu_e2ds', '2279009o_HR8489_pp_e2dsff_AB.fits']
run007 = ['obj_mk_tellu', 'tellu_e2ds', '2279010o_HR8489_pp_e2dsff_AB.fits']
run008 = ['obj_mk_tellu', 'tellu_e2ds', '2279017o_iotCyg_pp_e2dsff_AB.fits']
run009 = ['obj_mk_tellu', 'tellu_e2ds', '2279018o_iotCyg_pp_e2dsff_AB.fits']
run010 = ['obj_mk_tellu', 'tellu_e2ds', '2279019o_iotCyg_pp_e2dsff_AB.fits']
run011 = ['obj_mk_tellu', 'tellu_e2ds', '2279020o_iotCyg_pp_e2dsff_AB.fits']
run012 = ['obj_mk_tellu', 'tellu_e2ds', '2279104o_HD130917_pp_e2dsff_AB.fits']
run013 = ['obj_mk_tellu', 'tellu_e2ds', '2279197o_HD130917_pp_e2dsff_AB.fits']
run014 = ['obj_fit_tellu', 'tellu_e2ds', '2278951o_betSer_pp_e2dsff_AB.fits']
run015 = ['obj_fit_tellu', 'tellu_e2ds', '2278952o_betSer_pp_e2dsff_AB.fits']