# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# Test cal_CCF  on Gl699
run018a = ['cal_CCF_E2DS_spirou', 'TEST4/20180527', '2279680o_pp_e2dsff_AB_tellu_corrected.fits', 'gl581_Sep18_cleaned.mas', -110, 30, 0.5]
run018b = ['cal_CCF_E2DS_FP_spirou', 'TEST4/20180527', '2279680o_pp_e2dsff_AB_tellu_corrected.fits', 'gl581_Sep18_cleaned.mas', -110, 30, 0.5]

