# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# Requires Cal_Test.run and Tellu_Test.run to be run
# extracts out Gl699 from August and May dates + tellurics from May
# makes telluric maps for May, then correct tellurics on all Gl6999
# then produces template of Gl699

# pre-processing
run000a = ['cal_preprocess_spirou', 'TEST3/20180526', '*.fits']
run000b = ['cal_preprocess_spirou', 'TEST4/20180527', '*.fits']

# Calibrations
run001 = ['cal_DARK_spirou', 'TEST3/20180526', '2279303d_pp.fits']
run002 = ['cal_BADPIX_spirou', 'TEST3/20180526', '2279321f_pp.fits', '2279303d_pp.fits']
run003a = ['cal_loc_RAW_spirou', 'TEST3/20180526', '2279312f_pp.fits']
run003b = ['cal_loc_RAW_spirou', 'TEST3/20180526', '2279307f_pp.fits']
run005a = ['cal_SLIT_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run005b = ['cal_SHAPE_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run006 = ['cal_FF_RAW_spirou', 'TEST3/20180526', '2279321f_pp.fits']

# Extract the HC's/FP's
run007a = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run007b = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279330c_pp.fits']

# Run Wave solution analysis
run008a = ['cal_HC_E2DS_EA_spirou', 'TEST3/20180526', '2279330c_pp_e2ds_AB.fits']
run008b = ['cal_HC_E2DS_EA_spirou', 'TEST3/20180526', '2279330c_pp_e2ds_C.fits']
run009a = ['cal_WAVE_E2DS_EA_spirou', 'TEST3/20180526', '2279327a_pp_e2ds_AB.fits', '2279330c_pp_e2ds_AB.fits']
run009b = ['cal_WAVE_E2DS_EA_spirou', 'TEST3/20180526', '2279327a_pp_e2ds_C.fits', '2279330c_pp_e2ds_C.fits']

# Extract the tellurics
run010a = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279540o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279541o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279542o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279535o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279536o_pp.fits']

# Extract the science
run011a = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279680o_pp.fits']
run011b = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279681o_pp.fits']
run011c = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279682o_pp.fits']
run011d = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279683o_pp.fits']
run011e = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279684o_pp.fits']
run011f = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295545o_pp.fits']
run011g = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295546o_pp.fits']
run011h = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295547o_pp.fits']
run011i = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295548o_pp.fits']
run011j = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295549o_pp.fits']
run011k = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295550o_pp.fits']

# Run Make telluric recipes
run012a = ['obj_mk_tellu', 'TEST4/20180527', '2279540o_pp_e2dsff_AB.fits']
run012b = ['obj_mk_tellu', 'TEST4/20180527', '2279541o_pp_e2dsff_AB.fits']
run012c = ['obj_mk_tellu', 'TEST4/20180527', '2279542o_pp_e2dsff_AB.fits']
run012d = ['obj_mk_tellu', 'TEST4/20180527', '2279535o_pp_e2dsff_AB.fits']
run012e = ['obj_mk_tellu', 'TEST4/20180527', '2279536o_pp_e2dsff_AB.fits']

# Run Fit telluric recipes on Gl699
run013a = ['obj_fit_tellu', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']
run013b = ['obj_fit_tellu', 'TEST4/20180527', '2279681o_pp_e2dsff_AB.fits']
run013c = ['obj_fit_tellu', 'TEST4/20180527', '2279682o_pp_e2dsff_AB.fits']
run013d = ['obj_fit_tellu', 'TEST4/20180527', '2279683o_pp_e2dsff_AB.fits']
run013e = ['obj_fit_tellu', 'TEST4/20180527', '2279684o_pp_e2dsff_AB.fits']
run013f = ['obj_fit_tellu', 'TEST2/20180805', '2295545o_pp_e2dsff_AB.fits']
run013g = ['obj_fit_tellu', 'TEST2/20180805', '2295546o_pp_e2dsff_AB.fits']
run013h = ['obj_fit_tellu', 'TEST2/20180805', '2295547o_pp_e2dsff_AB.fits']
run013i = ['obj_fit_tellu', 'TEST2/20180805', '2295548o_pp_e2dsff_AB.fits']
run013j = ['obj_fit_tellu', 'TEST2/20180805', '2295549o_pp_e2dsff_AB.fits']
run013k = ['obj_fit_tellu', 'TEST2/20180805', '2295550o_pp_e2dsff_AB.fits']

# Run make obj template on Gl699
run014 = ['obj_mk_obj_template', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']

# Test cal_CCF  on Gl699
# run015a = ['cal_CCF_E2DS_spirou', 'TEST4/20180527', '2279680o_pp_e2dsff_AB_tellu_corrected.fits', 'masque_sept18.mas', -110, 30, 0.5]


