# file generated by setuptools-scm
# don't change, don't track in version control
__version__ = version = "0.8.200.dev46+ge8b425bfc.d20260325"
__version_tuple__ = version_tuple = (0, 8, 200, 'dev46', 'ge8b425bfc.d20260325')
__date__ = "2026-03-25"
