# file generated by setuptools-scm
# don't change, don't track in version control
__version__ = version = "0.8.251.dev17+g07f8c138d.d20260516"
__version_tuple__ = version_tuple = (0, 8, 251, 'dev17', 'g07f8c138d.d20260516')
__date__ = "2026-05-15"
