# file generated by setuptools-scm
# don't change, don't track in version control
__version__ = version = "0.7.297.dev119+g2b4c66b4b.d20260506"
__version_tuple__ = version_tuple = (0, 7, 297, 'dev119', 'g2b4c66b4b.d20260506')
__date__ = "2026-05-06"
