# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)

# requires Cal_Test.run to be run first
# Just extracts tellurics, makes telluric maps and corrects tellurics in
# one telluric, then runs cal_CCF to test output (All from July/August)

# pre-processing
run000a = ['cal_preprocess_spirou', 'TEST2/20180731', '*.fits']
run000b = ['cal_preprocess_spirou', 'TEST2/20180801', '*.fits']
run000c = ['cal_preprocess_spirou', 'TEST2/20180802', '*.fits']
run000d = ['cal_preprocess_spirou', 'TEST2/20180803', '*.fits']
run000e = ['cal_preprocess_spirou', 'TEST2/20180804', '*.fits']
run000f = ['cal_preprocess_spirou', 'TEST2/20180805', '*.fits']
run000g = ['cal_preprocess_spirou', 'TEST3/20180526', '*.fits']
run000h = ['cal_preprocess_spirou', 'TEST4/20180527', '*.fits']

# Calibrations (For files not using cal_CCF calibrations)
run001 = ['cal_DARK_spirou', 'TEST3/20180526', '2279303d_pp.fits']
run002 = ['cal_BADPIX_spirou', 'TEST3/20180526', '2279321f_pp.fits', '2279303d_pp.fits']
run003a = ['cal_loc_RAW_spirou', 'TEST3/20180526', '2279312f_pp.fits']
run003b = ['cal_loc_RAW_spirou', 'TEST3/20180526', '2279307f_pp.fits']
run005a = ['cal_SLIT_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run005b = ['cal_SHAPE_spirou', 'TEST3/20180526', '2279330c_pp.fits', '2279327a_pp.fits']
run006 = ['cal_FF_RAW_spirou', 'TEST3/20180526', '2279321f_pp.fits']

# Extract the HC's/FP's
run007a = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279327a_pp.fits']
run007b = ['cal_extract_RAW_spirou', 'TEST3/20180526', '2279330c_pp.fits']

# Run Wave solution analysis
run008a = ['cal_HC_E2DS_EA_spirou', 'TEST3/20180526', '2279330c_pp_e2ds_AB.fits']
run008b = ['cal_HC_E2DS_EA_spirou', 'TEST3/20180526', '2279330c_pp_e2ds_C.fits']
run008c = ['cal_WAVE_E2DS_EA_spirou', 'TEST3/20180526', '2279327a_pp_e2ds_AB.fits', '2279330c_pp_e2ds_AB.fits']
run008d = ['cal_WAVE_E2DS_EA_spirou', 'TEST3/20180526', '2279327a_pp_e2ds_C.fits', '2279330c_pp_e2ds_C.fits']

# Extract the tellurics
run009a = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294972o_pp.fits']
run009b = ['cal_extract_RAW_spirou', 'TEST2/20180731', '2294973o_pp.fits']
run009c = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295080o_pp.fits']
run009d = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295118o_pp.fits']
run009e = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295124o_pp.fits']
run009f = ['cal_extract_RAW_spirou', 'TEST2/20180801', '2295126o_pp.fits']
run009g = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295200o_pp.fits']
run009h = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295243o_pp.fits']
run009i = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295248o_pp.fits']
run009j = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295265o_pp.fits']
run009k = ['cal_extract_RAW_spirou', 'TEST2/20180802', '2295266o_pp.fits']
run009l = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295353o_pp.fits']
run009m = ['cal_extract_RAW_spirou', 'TEST2/20180803', '2295358o_pp.fits']
run009n = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295412o_pp.fits']
run009o = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295470o_pp.fits']
run009p = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295479o_pp.fits']
run009q = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295480o_pp.fits']
run009r = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295485o_pp.fits']
run009s = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295486o_pp.fits']
run009t = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295487o_pp.fits']
run009u = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295492o_pp.fits']
run009v = ['cal_extract_RAW_spirou', 'TEST2/20180804', '2295506o_pp.fits']
run010a = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279540o_pp.fits']
run010b = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279541o_pp.fits']
run010c = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279542o_pp.fits']
run010d = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279535o_pp.fits']
run010e = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279536o_pp.fits']

# Extract the science
run011a = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279680o_pp.fits']
run011b = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279681o_pp.fits']
run011c = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279682o_pp.fits']
run011d = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279683o_pp.fits']
run011e = ['cal_extract_RAW_spirou', 'TEST4/20180527', '2279684o_pp.fits']
run011f = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295545o_pp.fits']
run011g = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295546o_pp.fits']
run011h = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295547o_pp.fits']
run011i = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295548o_pp.fits']
run011j = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295549o_pp.fits']
run011k = ['cal_extract_RAW_spirou', 'TEST2/20180805', '2295550o_pp.fits']

# Run Make telluric db recipe (wrapper)
run013 = ['obj_mk_tellu_db', '1']

# Run Fit telluric recipes on Gl699
run014a = ['obj_fit_tellu', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']
run014b = ['obj_fit_tellu', 'TEST4/20180527', '2279681o_pp_e2dsff_AB.fits']
run014c = ['obj_fit_tellu', 'TEST4/20180527', '2279682o_pp_e2dsff_AB.fits']
run014d = ['obj_fit_tellu', 'TEST4/20180527', '2279683o_pp_e2dsff_AB.fits']
run014e = ['obj_fit_tellu', 'TEST4/20180527', '2279684o_pp_e2dsff_AB.fits']
run014f = ['obj_fit_tellu', 'TEST2/20180805', '2295545o_pp_e2dsff_AB.fits']
run014g = ['obj_fit_tellu', 'TEST2/20180805', '2295546o_pp_e2dsff_AB.fits']
run014h = ['obj_fit_tellu', 'TEST2/20180805', '2295547o_pp_e2dsff_AB.fits']
run014i = ['obj_fit_tellu', 'TEST2/20180805', '2295548o_pp_e2dsff_AB.fits']
run014j = ['obj_fit_tellu', 'TEST2/20180805', '2295549o_pp_e2dsff_AB.fits']
run014k = ['obj_fit_tellu', 'TEST2/20180805', '2295550o_pp_e2dsff_AB.fits']

# Run make obj template on Gl699
run015 = ['obj_mk_obj_template', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']

# Run Fit telluric recipes on Gl699
run016a = ['obj_fit_tellu', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']
run016b = ['obj_fit_tellu', 'TEST4/20180527', '2279681o_pp_e2dsff_AB.fits']
run016c = ['obj_fit_tellu', 'TEST4/20180527', '2279682o_pp_e2dsff_AB.fits']
run016d = ['obj_fit_tellu', 'TEST4/20180527', '2279683o_pp_e2dsff_AB.fits']
run016e = ['obj_fit_tellu', 'TEST4/20180527', '2279684o_pp_e2dsff_AB.fits']
run016f = ['obj_fit_tellu', 'TEST2/20180805', '2295545o_pp_e2dsff_AB.fits']
run016g = ['obj_fit_tellu', 'TEST2/20180805', '2295546o_pp_e2dsff_AB.fits']
run016h = ['obj_fit_tellu', 'TEST2/20180805', '2295547o_pp_e2dsff_AB.fits']
run016i = ['obj_fit_tellu', 'TEST2/20180805', '2295548o_pp_e2dsff_AB.fits']
run016j = ['obj_fit_tellu', 'TEST2/20180805', '2295549o_pp_e2dsff_AB.fits']
run016k = ['obj_fit_tellu', 'TEST2/20180805', '2295550o_pp_e2dsff_AB.fits']

# Run make obj template on Gl699
run017 = ['obj_mk_obj_template', 'TEST4/20180527', '2279680o_pp_e2dsff_AB.fits']

# Test cal_CCF  on Gl699
run018a = ['cal_CCF_E2DS_spirou', 'TEST4/20180527', '2279682o_pp_e2dsff_AB_tellu_corrected.fits', 'masque_sept18.mas', -110, 30, 0.5]

