[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ['version', 'scripts']
name = 'aperocore'
authors = [
    {name = 'Neil Cook', email = 'neil.james.cook@gmail.com'},
]
description = 'APERO is a pipeline designed to reduce astrophysical observations (specifically from echelle spectrographs). It is the offical pipeline for SPIRou and is also used for NIRPS.'
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = 'LICENSE'}
requires-python = "==3.11.*"
dependencies = [
    "astropy==7.0.1",
    "ipython==8.32.0",
    "ipdb==0.13.13",
    "Bottleneck==1.4.2",
    "duckdb==1.2.0",
    "GitPython==3.1.44",
    "numba==0.61.0",
    "numexpr==2.10.2",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pandastable==0.13.1",
    "pandasql==0.7.3",
    "psutil==7.0.0",
    "PyYAML==6.0.2",
    "PyMySQL==1.1.1",
    "ruamel.yaml==0.18.10",
    "scipy==1.15.2",
    "SQLAlchemy==2.0.38",
    "sqlalchemy_utils==0.41.2",
    "statsmodels==0.14.4",
    "tqdm==4.67.1",
    "wget==3.2",
    "yagmail==0.15.293",
]

[project.urls]
Homepage = 'http://apero.exoplanets.ca'
Repository = 'https://github.com/njcuk9999/apero-drs'

