# define run
#    (Format = [recipe, night_name, argument1, argument2, argument3, ...])
# runs must start with runXXX where XXX is a number (no more than 999 runs else XXXX)
run000 = ['cal_preprocess_spirou', 'AT5/20180409', '*.fits']
run001 = ['cal_DARK_spirou', 'AT5/20180409', 'dark_dark_001_pp.fits']
run002 = ['cal_BADPIX_spirou', 'AT5/20180409', 'flat_flat_001_pp.fits', 'dark_dark_001_pp.fits']
run003a = ['cal_loc_RAW_spirou', 'AT5/20180409', 'dark_flat_001_pp.fits']
run003b = ['cal_loc_RAW_spirou', 'AT5/20180409', 'flat_dark_001_pp.fits']
run005 = ['cal_SLIT_spirou', 'AT5/20180409', 'fp_fp_001_pp.fits']
run006 = ['cal_FF_RAW_spirou', 'AT5/20180409', 'flat_flat_001_pp.fits']
run007a = ['cal_extract_RAW_spirou', 'AT5/20180409', 'fp_fp_001_pp.fits']
# These two are fake (copies of fp_fp_001)
run007b = ['cal_extract_RAW_spirou', 'AT5/20180409', 'fp_fp_002_pp.fits']
run007c = ['cal_extract_RAW_spirou', 'AT5/20180409', 'fp_fp_003_pp.fits']
run007d = ['cal_extract_RAW_spirou', 'AT5/20180409', 'hcone_hcone_001_pp.fits']
run008 = ['cal_HC_E2DS_spirou', 'AT5/20180409', 'hcone_hcone_001_pp_e2dsff_AB.fits']
run009a = ['cal_WAVE_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2dsff_AB.fits', 'hcone_hcone_001_pp_e2dsff_AB.fits', ]
# run009b = ['cal_WAVE_NEW_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2dsff_AB.fits', 'hcone_hcone_001_pp_e2dsff_AB.fits']
run010a = ['cal_DRIFT_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2ds_AB.fits']
run010b = ['cal_DRIFTPEAK_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2ds_AB.fits']
run011 = ['cal_CCF_E2DS_spirou', 'AT5/20180409', 'hcone_hcone_001_pp_e2ds_C.fits', 'UrNe.mas', 0, 10, 0.1]
run012 = ['cal_exposure_meter', 'AT5/20180409', 'flat_dark_001_pp.fits']
run013a = ['off_listing_RAW_spirou', 'AT5/20180409']
run013b = ['off_listing_REDUC_spirou', 'AT5/20180409']
run014 = ['visu_RAW_spirou', 'AT5/20180409', 'fp_fp_001_pp.fits']
run015 = ['visu_E2DS_spirou', 'AT5/20180409', 'fp_fp_001_pp_e2ds_AB.fits']
# run016 = ['pol_spirou', 'TEST/20180528', '2279383o_pp_e2dsff_A.fits', '2279384o_pp_e2dsff_B.fits', '2279386o_pp_e2dsff_A.fits', '2279383o_pp_e2dsff_B.fits', '2279385o_pp_e2dsff_A.fits', '2279386o_pp_e2dsff_B.fits', '2279384o_pp_e2dsff_A.fits', '2279385o_pp_e2dsff_B.fits']

